name: "A+: CI"

permissions:
  contents: write

on:
  workflow_dispatch:
  workflow_call:
  pull_request:
  push:
    branches:
      - main

jobs:
  cargo-build:
    name: Cargo Build
    runs-on: ubuntu-latest

    steps:
      - name: Fetch Repository
        uses: actions/checkout@v4

      - name: Install stable toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Build rlib
        run: cd bluesim-rlib && cargo b --workspace --all-targets --all-features

      - name: Build rb_link
        run: cd rb_link && cargo b --workspace --all-targets --all-features

  cargo-fmt:
    name: Cargo fmt
    runs-on: ubuntu-latest

    steps:
      - name: Fetch Repository
        uses: actions/checkout@v4

      - name: Install stable toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt

      - name: Rustfmt Check rlib
        run: cd bluesim-rlib && cargo fmt --all --check

      - name: Rustfmt Check rb_link
        run: cd rb_link && cargo fmt --all --check

  cargo-clippy:
    name: Cargo clippy
    runs-on: ubuntu-latest

    steps:
      - name: Fetch Repository
        uses: actions/checkout@v4

      - name: Install stable toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy

      - name: Clippy Check rlib
        run: cd bluesim-rlib && cargo clippy --workspace --all-targets --all-features -- -Dwarnings 

      - name: Clippy Check rb_link
        run: cd rb_link && cargo clippy --workspace --all-targets --all-features -- -Dwarnings 

  cargo-test:
    name: Cargo test
    runs-on: ubuntu-latest

    steps:
      - name: Fetch Repository
        uses: actions/checkout@v4

      - name: Install stable toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Cargo test rb_link
        run: cd rb_link && cargo test -- --test-threads=1

